use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest()),
    )
    .expect("tauri build failed");
    gen_skill_manifest();
    embed_app_manifest();
}

/// 内容与 tauri-build 默认应用清单（windows-app-manifest.xml）逐字一致：
/// 只有 Common-Controls v6 一条依赖声明。
const APP_MANIFEST_XML: &str = r#"<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
</assembly>
"#;

/// 清单统一由链接器嵌入所有目标（2026-09-25）：
/// tauri-build 默认只给 bin 经 RC 资源嵌清单，cargo 的 lib 测试 exe 不带清单 →
/// Windows 加载 comctl32 v5，缺 tauri 菜单库（muda）导入的 v6 独有函数
/// TaskDialogIndirect → 测试进程启动即 STATUS_ENTRYPOINT_NOT_FOUND (0xc0000139)，
/// `cargo test` 在 Windows 上全灭。且清单嵌法没有「仅测试」的作用域可用：
/// `rustc-link-arg-tests` 不作用于 lib 单元测试 exe；总体 `rustc-link-arg` 与
/// RC 清单并存会重资源（CVT1100 duplicate MANIFEST）。所以这里让 tauri-build
/// 不嵌清单（new_without_app_manifest），改由链接器为 bin 与测试 exe 嵌入
/// 同一份清单——内容与默认一致，应用行为不变。
#[cfg(target_env = "msvc")]
fn embed_app_manifest() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let manifest_path = out_dir.join("app-manifest.xml");
    fs::write(&manifest_path, APP_MANIFEST_XML).expect("写入 app-manifest.xml 失败");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest_path.display());
}

#[cfg(not(target_env = "msvc"))]
fn embed_app_manifest() {}

/// 把内置技能包（仓库 `skills/x-hub-extension`）的全部文件生成成
/// `(相对路径, include_bytes!(绝对路径))` 清单，供 `src/skills.rs` 编译期烘焙进二进制。
///
/// 单一真相源 = 仓库 `skills/x-hub-extension/`：skill 增删文件无需改 Rust 代码，
/// 重新构建即带上。清单写到 `$OUT_DIR/skill_files.rs`，由 skills.rs `include!` 进来。
fn gen_skill_manifest() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // 仓库根的 skills/x-hub-extension（src-tauri 的上一级）
    let root = manifest_dir
        .join("..")
        .join("skills")
        .join("x-hub-extension");

    let mut files: Vec<String> = Vec::new();
    if root.is_dir() {
        collect(&root, &root, &mut files);
    } else {
        println!(
            "cargo:warning=内置技能包目录不存在，Skills 功能将为空: {}",
            root.display()
        );
    }
    files.sort();

    // 目录本身也登记：新增文件时 Cargo 才能感知（目录 mtime 变化）
    println!("cargo:rerun-if-changed={}", root.display());

    let mut code = String::from(
        "// @generated by build.rs —— 内置技能包文件清单，勿手改\n\
         /// (相对路径（正斜杠）, 文件内容)；安装时按相对路径逐段建目录\n\
         pub static EMBEDDED_SKILL_FILES: &[(&str, &[u8])] = &[\n",
    );
    for rel in &files {
        let abs = root.join(rel);
        println!("cargo:rerun-if-changed={}", abs.display());
        code.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            rel.replace('\\', "/"),
            abs.to_string_lossy().replace('\\', "/")
        ));
    }
    code.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("skill_files.rs");
    fs::write(&out, code).expect("写入 skill_files.rs 失败");
}

/// 递归收集目录下所有文件的相对路径
fn collect(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            out.push(rel.to_string_lossy().into_owned());
        }
    }
}
